name: RezineSMP
version: '1.0-SNAPSHOT'
main: me.foxils.rezineSMP.RezineSMP
api-version: '1.21'
authors: [ Foxils @foxils. on Discord ]
description: Does some stuff idfk yet.

depend:
  - foxutils-items
  - foxutils-hud

commands:
  getitemlevel:
    description: Get the level of the current ArtifactItem in your hand
    usage: /<command>
    permission: op
    aliases: [getlevel, levelget]
  setitemlevel:
    description: Set the level of the current ArtifactItem in your hand
    usage: /<command> <level>
    permission: op
    aliases: [setlevel, levelset]